language: pebblec
sudo: false
before_script: bash ./before_install.sh
script: bash ./build.sh
cache:
  directories:
    - $HOME/pebble-dev
    - $HOME/.cache/pip
addons:
  apt:
    packages:
    - python2.7-dev
    - python-pip
    - python-virtualenv
language: node_js
node_js:
  - node
